### ISSUE TITLE
The project website has a https bad certificate: https://www.korvo.gatech.edu/software

### ISSUE THREAD

**Issue by yurivict** [GTkorvo/atl#30]
Browsers complain:

Websites prove their identity via certificates. Firefox does not trust this site because it uses a certificate that is not valid for www.korvo.gatech.edu. The certificate is only valid for the following names: hosting.gatech.edu, *.ae.gatech.edu, *.arch.gatech.edu, *.arcs.gatech.edu, *.bc.gatech.edu, *.biology.gatech.edu, *.biosci.gatech.edu, *.biosciences.gatech.edu, *.bme.gatech.edu, *.campusservices.gatech.edu, *.cc.gatech.edu, *.ce.gatech.edu, *.ceismc.gatech.edu, *.chbe.gatech.edu, *.chemistry.gatech.edu, *.cidi.gatech.edu, *.coe.gatech.edu, *.cos.gatech.edu, *.create-x.gatech.edu, *.cse.gatech.edu, *.ctl.gatech.edu, *.design.gatech.edu, *.eas.gatech.edu, *.ebb.gatech.edu, *.ece.gatech.edu, *.econ.gatech.edu, *.ehs.gatech.edu, *.em.gatech.edu, *.es.gatech.edu, *.finaid.gatech.edu, *.fis.gatech.edu, *.gatech.edu, *.gtmi.gatech.edu, *.gtorg.gatech.edu, *.gtri.gatech.edu, *.gvu.gatech.edu, *.health.gatech.edu, *.hosting.gatech.edu, *.housing.gatech.edu, *.hsoc.gatech.edu, *.hts.gatech.edu, *.iac.gatech.edu, *.ibb.gatech.edu, *.ic.gatech.edu, *.id.gatech.edu, *.inta.gatech.edu, *.irp.gatech.edu, *.isye.gatech.edu, *.library.gatech.edu, *.lmc.gatech.edu, *.math.gatech.edu, *.me.gatech.edu, *.modlangs.gatech.edu, *.mse.gatech.edu, *.music.gatech.edu, *.nre.gatech.edu, *.nremp.gatech.edu, *.oie.gatech.edu, *.oit.gatech.edu, *.physics.gatech.edu, *.planning.gatech.edu, *.psych.gatech.edu, *.psychology.gatech.edu, *.registrar.gatech.edu, *.research.gatech.edu, *.scheller.gatech.edu, *.scl.gatech.edu, *.scs.gatech.edu, *.security.gatech.edu, *.spp.gatech.edu, *.studentcenter.gatech.edu, *.studentlife.gatech.edu, *.wrecktechs.gatech.edu
 
Error code: [SSL_ERROR_BAD_CERT_DOMAIN](about:certerror?e=nssBadCert&u=https%3A//www.korvo.gatech.edu/software&c=UTF-8&d=%20#certificateErrorDebugInformation)

**Comment by eisenhauer** [comment]
Original project under which this package was created has been dormant for some time.  Project website will not be migrated to a safer hosting platform, so we've just removed the link to the now-defunct website.
